[package]
name = "p2p_chat_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
data-encoding = "2.8.0"
iroh = "0.34.0"
iroh-gossip = "0.34.1"
rand = "0.8"
rand_core = "0.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.43.0"
